/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/laptop-model.gltf --transform 
Files: public/laptop-model.gltf [606.79KB] > /Users/chrisb/Desktop/r3f portfolio/laptop-model-transformed.glb [423.53KB] (30%)
*/

import React from 'react';
import { Html, useGLTF } from '@react-three/drei';

export function Model(props) {
	const { nodes, materials } = useGLTF('/laptop-model-transformed.glb');
	return (
		<group {...props} dispose={null} position-y={-1.2}>
			{/* Html inside R3F */}
			<Html
				transform
				wrapperClass='html-frame'
				distanceFactor={1.17}
				position={[0, 1.56, -1.4]}
				rotation-x={-0.256}>
				<iframe src='https://christian-bermeo.netlify.app/' />
			</Html>

			<mesh
				geometry={nodes.Macbook.geometry}
				material={materials.PaletteMaterial001}
				position={[0, 0.519, 0]}
				scale={0.103}
			/>
			<mesh
				geometry={nodes.Top.geometry}
				material={materials.PaletteMaterial001}
				position={[0.001, 0.471, -1.077]}
				rotation={[1.311, 0, 0]}
				scale={0.599}
			/>
			<mesh
				geometry={nodes.AppleLogo000.geometry}
				material={materials.PaletteMaterial002}
				position={[0.004, 1.493, -1.418]}
				rotation={[-1.831, 0, -Math.PI]}
				scale={0.347}
			/>
		</group>
	);
}

useGLTF.preload('./laptop-model-transformed.glb');
